// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4aT30rNBsyFZOd92a4dlJVINgsA08kJ8',
    appId: '1:119720707462:web:94a21865990490b3795807',
    messagingSenderId: '119720707462',
    projectId: 'careerboost-f8577',
    authDomain: 'careerboost-f8577.firebaseapp.com',
    storageBucket: 'careerboost-f8577.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk1OEYU39H0oswkY_9_BtSKoN_G0L6UX0',
    appId: '1:119720707462:android:6062e1957d1cba34795807',
    messagingSenderId: '119720707462',
    projectId: 'careerboost-f8577',
    storageBucket: 'careerboost-f8577.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6168EYlWkHyxQTnhLPxBoyMxKkQNm8s4',
    appId: '1:119720707462:ios:6a24d23da23ccf81795807',
    messagingSenderId: '119720707462',
    projectId: 'careerboost-f8577',
    storageBucket: 'careerboost-f8577.firebasestorage.app',
    iosBundleId: 'com.example.cb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6168EYlWkHyxQTnhLPxBoyMxKkQNm8s4',
    appId: '1:119720707462:ios:6a24d23da23ccf81795807',
    messagingSenderId: '119720707462',
    projectId: 'careerboost-f8577',
    storageBucket: 'careerboost-f8577.firebasestorage.app',
    iosBundleId: 'com.example.cb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4aT30rNBsyFZOd92a4dlJVINgsA08kJ8',
    appId: '1:119720707462:web:9827be29862cf2c1795807',
    messagingSenderId: '119720707462',
    projectId: 'careerboost-f8577',
    authDomain: 'careerboost-f8577.firebaseapp.com',
    storageBucket: 'careerboost-f8577.firebasestorage.app',
  );
}
